#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=15

CONF="duck"
PROG="/usr/bin/duck"
LOG="/var/log/duck/duck.log"

start_service() {
	config_load "$CONF"
	local enabled
	config_get_bool enabled "global" "enabled" "0"
	[ "$enabled" -eq "1" ] || return 0
	local listen_addr log_maxbackups log_maxsize
	config_get listen_addr "global" "listen_addr" "0.0.0.0:2023"
	config_get log_maxbackups "global" "log_maxbackups" "1"
	config_get log_maxsize "global" "log_maxsize" "5"
	mkdir -p /var/log/duck
	procd_open_instance
	procd_set_param command "$PROG" run
	procd_append_param command --config "/etc/duck/"
	procd_append_param command --listen "$listen_addr"
	procd_append_param command --logfile "$LOG"
	procd_append_param command --logfile-maxbackups "$log_maxbackups"
	procd_append_param command --logfile-maxsize "$log_maxsize"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	killall -q duck 2>/dev/null || true
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}
