include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-duck
PKG_VERSION:=0
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for duck - dae proxy manager
LUCI_DEPENDS:=+duck
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk
# call BuildPackage - OpenWrt buildroot signature

